#!/bin/bash
############################################################
# Set a new Powerlimit for NVIDIA PGUs                     #
# on ethos or other Linux, which has nvidia-smi installed. #
############################################################
# Usage: ./NVIDIA-power-limit $POWER_LIMIT                 #
# $POWER_LIMIT could be 150 or 99.5                        #
############################################################
# Autor: Gery (gery@net6.at)                               #
#                                                          #
# Thank you for any donations.                             #
# ETH: 0x378EF90Dc697c2397327dB2b8F665387C40d1Ad9          #
# Zcash: t1chPVQiV8DcRJESnbh5xjFAYQ6XL3Vz7No               #
# BTC: 1GEybheHJtZ4SdWiW3FQa33BE4826cvptQ                  #
############################################################


NV_COUNT=`lspci | grep NVIDIA | grep VGA | wc -l`

if [[ $1 != "" ]]; then
MAX_WATT=$1

echo "DETECT: $NV_COUNT NVIDIA GPUs."

for ((i=1;i<=$NV_COUNT;i++)) do
GPU_NUM=$(($i-1))
echo ""
echo "SET PowerLimit to $MAX_WATT Watt on NVIDIA GPU$GPU_NUM."
sudo nvidia-smi -i $GPU_NUM -pl $MAX_WATT >> /dev/null
done

echo ""
echo -e "\033[0;32mPowerLimit was set to: \033[1;32m$MAX_WATT \033[0;32mWatt.\033[0m"
echo ""
else
MIN_POW=`nvidia-smi -a| grep "Min Power Limit" |awk '{print $5;}' | sort -n -r |head -n 1`
MAX_POW=`nvidia-smi -a| grep "Max Power Limit" |awk '{print $5;}' | sort -n |head -n 1`
echo ""
echo -e "\033[1;31mPowerLimit unchanged.\033[0m"
echo ""
echo "To set a new powerlimit run $0 WATT_LIMIT (Example for 100 Watt -> $0 100 )"
echo "You can set your PowerLimit between $MIN_POW Watt and $MAX_POW Watt."
echo ""
echo -e "\033[1;33mPower Limit Min: \033[1;31m$MIN_POW \033[1;33mWatt\033[0m"
echo -e "\033[1;33mPower Limit Max: \033[1;32m$MAX_POW \033[1;33mWatt\033[0m"
echo ""
fi

echo "+-----------------------------------------------------------------------------+"
echo "| NVIDIA GPU DETAILS:   -   by nvidia-smi usage   |      GPU - Count: $NV_COUNT       |"
echo "+-----------------------------------------------------------------------------+"
echo "| FAN | TMP | Perf | WATT / MAX W| VRAM USED /  VRAM   | GPU-Util  |  Compute |"
echo "+-----------------------------------------------------------------------------+"
nvidia-smi | grep W
echo "+-----------------------------------------------------------------------------+"
echo ""


exit 0

